2025/04/09 10:44:48 Logging started...
2025/04/09 10:44:48 Logging started...
2025/04/09 10:44:48 Application is starting...
2025/04/09 10:44:48 Database connection established.
2025/04/09 10:44:48 Seeding database with predetermined words...
2025/04/09 10:44:48 Database seeding completed.
2025/04/09 10:44:48 Datadog tracer started
2025/04/09 10:44:48 Go application started successfully
2025/04/09 10:44:48 Starting server on :8080...
2025/04/09 10:51:18 Datadog Tracer v1.69.1 ERROR: failure sending traces (attempt 1), will retry: Post "http://localhost:8136/v0.4/traces": dial tcp [::1]:8136: connect: connection refused, 1 additional messages skipped (first occurrence: 09 Apr 25 10:50 EDT)
2025/04/09 10:51:18 Datadog Tracer v1.69.1 ERROR: lost 1 traces: Post "http://localhost:8136/v0.4/traces": dial tcp [::1]:8136: connect: connection refused, 1 additional messages skipped (first occurrence: 09 Apr 25 10:50 EDT)
2025/04/09 10:52:30 Datadog Tracer v1.69.1 ERROR: lost 1 traces: Post "http://localhost:8136/v0.4/traces": dial tcp [::1]:8136: connect: connection refused, 2 additional messages skipped (first occurrence: 09 Apr 25 10:51 EDT)
2025/04/09 10:52:30 Datadog Tracer v1.69.1 ERROR: failure sending traces (attempt 1), will retry: Post "http://localhost:8136/v0.4/traces": dial tcp [::1]:8136: connect: connection refused, 2 additional messages skipped (first occurrence: 09 Apr 25 10:51 EDT)
2025/04/09 10:56:26 Datadog Tracer v1.69.1 ERROR: failure sending traces (attempt 1), will retry: Post "http://localhost:8136/v0.4/traces": dial tcp [::1]:8136: connect: connection refused (occurred: 09 Apr 25 10:55 EDT)
2025/04/09 10:56:26 Datadog Tracer v1.69.1 ERROR: lost 1 traces: Post "http://localhost:8136/v0.4/traces": dial tcp [::1]:8136: connect: connection refused (occurred: 09 Apr 25 10:55 EDT)
2025/04/09 10:57:50 Datadog Tracer v1.69.1 ERROR: failure sending traces (attempt 1), will retry: Post "http://localhost:8136/v0.4/traces": dial tcp [::1]:8136: connect: connection refused (occurred: 09 Apr 25 10:56 EDT)
2025/04/09 10:57:50 Datadog Tracer v1.69.1 ERROR: lost 1 traces: Post "http://localhost:8136/v0.4/traces": dial tcp [::1]:8136: connect: connection refused (occurred: 09 Apr 25 10:56 EDT)
